### PR TITLE
seeding script edit

### PR DESCRIPTION
**Pull request by eugkim1997**

### CODE REVIEW

**Review by jasonckassahn — COMMENTED** [review]
1. Inside generateImageURL and generateImageDescription, since the arrays are declared inside of those functions, i believe you are creating a new array each time those are called, which will probably contribute to memory footprint as your i goes up. you may want to move those arrays into the global scope or into the calling function so that they are only each declared once
2. Similar pattern with all of the functions called in generateProperty, you might want to consider moving any array declarations into the top level function instead of the functions that are called repeatedly
3. I am a little lost on how your generateImageIndexes and generateImageArray helpers are being used, could you step me through how they function and how their outputs are being utilized?

**Comment by eugkim1997** [comment]
Made image arrays global, reviewed generateImageIndexes and generateImageArray helpers

**Comment by eugkim1997** [comment]
moved rest of reused arrays into global scope

**Review by jasonckassahn — APPROVED** [review]
Looks great, approved

**Pull request merged**
